"""RefreshSession

Revision ID: d5abee2ec6a2
Revises: dc62c85e79de
Create Date: 2024-03-22 22:36:33.592920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5abee2ec6a2"
down_revision: Union[str, None] = "dc62c85e79de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refreshsessions",
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("expires_in", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refreshsessions_id"), "refreshsessions", ["id"], unique=False
    )
    op.drop_table("userprofiles")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_table(
        "userprofiles",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_avatar_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_bio", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_location", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_website", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_github", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="userprofiles_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="userprofiles_pkey"),
    )
    op.drop_index(op.f("ix_refreshsessions_id"), table_name="refreshsessions")
    op.drop_table("refreshsessions")
    # ### end Alembic commands ###
