repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff format --config /backend/users-service/pyproject.toml .
        language: system
        types: [ python3 ]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy --config-file backend/users-service/pyproject.toml .
        language: system
        types: [ python3 ]
        pass_filenames: false
