version: "3.8"

services:
  users-service:
    image: litestar-users-service:latest
    container_name: litestar-users
    build:
      context: ./users-service/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./users-service/app/:/service/app/
    restart: always
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - backend-network

  postgres:
    container_name: litestar-users-db
    image: postgres:16-alpine
    restart: always
    env_file: ./.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - ./postgres/docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: litestar-users-cache
    restart: always
    env_file: ./.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"
    # volumes:
    #   - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server
    networks:
      - backend-network

  #  nginx:
  #    image: nginx:latest
  #    container_name: proxy
  #    restart: always
  #    ports:
  #      - "80:80"
  #    volumes:
  #      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
  #    networks:
  #      - backend

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: litestar-message-broker
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      # - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - backend-network

  # email_service:
  #   image: email-service:latest
  #   container_name: email-service
  #   build:
  #     context: ./email-service/
  #     dockerfile: Dockerfile
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./email-service/
  #         target: ./app/
  #   ports:
  #     - "50:50"
  #   restart: always
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - backend

networks:
  backend-network:
    name: backend-network
    driver: bridge