"""Up models

Revision ID: 9d31b64741b9
Revises: eba18da8bd69
Create Date: 2024-02-20 18:08:33.063176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d31b64741b9"
down_revision: Union[str, None] = "eba18da8bd69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "referral_code", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "referral_code", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
