"""Add fk 2024-04-04 17:30

Revision ID: 5a38f9e70039
Revises: 2e771413244e
Create Date: 2024-04-04 17:30:14.183302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a38f9e70039'
down_revision: Union[str, None] = '2e771413244e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
