"""Initial 30-03-2024 11:00

Revision ID: 7dc725447acb
Revises: b7e294f49c45
Create Date: 2024-03-31 11:00:13.984155

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7dc725447acb"
down_revision: Union[str, None] = "b7e294f49c45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
                    sa.Column("hashed_password", sa.String(), nullable=False),
                    sa.Column("email", sa.String(), nullable=False),
                    sa.Column("is_active", sa.Boolean(), nullable=False),
                    sa.Column("is_superuser", sa.Boolean(), nullable=False),
                    sa.Column("is_activated", sa.Boolean(), nullable=False),
                    sa.Column("id", sa.Integer(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table("refreshsessions",
                    sa.Column("refresh_token", sa.String(), nullable=False),
                    sa.Column("expires_in", sa.Integer(), nullable=False),
                    sa.Column("user_id", sa.Integer(), nullable=False),
                    sa.Column("id", sa.Integer(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
                    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_index(op.f("ix_refreshsessions_id"), "refreshsessions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refreshsessions_id"), table_name="refreshsessions")
    op.drop_table("refreshsessions")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
