version: "3.8"

services:
  fastapi-fullstack:
    image: fastapi:latest
    container_name: fast
    build:
      context: .
    ports:
      - 80:80
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - frontend
      - backend

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - source/scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    env_file: 
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis-data:${REDIS_DATA}
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge

volumes:
  db-data:

  redis-data:

