version: "3.8"

services:
  backend:
    image: fastapi:latest
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - frontend
      - backend

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    env_file: ./.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - /mnt/r/Work/projects/python/fastapi/source/backend/app/scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    env_file: ./.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis-data:${REDIS_DATA}
    networks:
      - backend
  
  # frontend:

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge

volumes:
  db-data:

  redis-data:

